import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { CTA, PageHero } from "@/components/SiteShell";

type PageData = { eyebrow:string; title:string; description:string; sections:{title:string; copy?:string; items?:string[]}[]; cta?:string };

const pages: Record<string, PageData> = {
  "inventory-replenishment-sprint": {
    eyebrow:"PRIMARY OFFERING", title:"Inventory Replenishment Decision Diagnostic", description:"A focused advisory engagement that evaluates how replenishment decisions are made today—across existing planning tools, planner overrides and execution—and identifies where rules, exception intelligence and AI can improve decision quality.",
    sections:[
      {title:"The decision we assess",copy:"Most retailers already have replenishment logic somewhere—in a planning platform, ERP, spreadsheet or planner workflow. The diagnostic evaluates whether that ecosystem consistently surfaces the right decision and where manual effort or overrides indicate a gap.",items:["Which SKU-location combinations genuinely need attention?","Where does the current tool recommend replenishment, hold or transfer?","Where and why are planners overriding the recommendation?","What quantity is actually executed?","Which exceptions or override patterns repeat?"]},
      {title:"What data we use",copy:"V1 starts with an agreed extract from the systems the retailer already uses. No new production application is required.",items:["SKU / product and store / location","Recent sales history","Current on-hand inventory","Incoming / open inventory","Lead time and pack size","Target WOS / safety stock / business rules where available","Current tool recommendation and quantity","Planner override quantity and reason","Actual executed quantity","Historical outcomes where available"]},
      {title:"What Averin delivers",copy:"The output is a consulting decision pack rather than deployed software.",items:["Replenishment Decision Map","Priority Exception Workbook","Current-tool vs planner-override vs Averin comparison","Data-quality and rule observations","Historical / policy assessment where data permits","AI and automation opportunity roadmap","Executive readout and planner workshop"]},
      {title:"How the engagement works",items:["Observe the current planner / buyer workflow","Agree the data extract and decision scope","Map retailer policies, thresholds and existing-system logic","Run independent exception and decision analysis","Review top differences and overrides with planners","Refine findings using planner context","Deliver decision pack and practical improvement roadmap"]},
      {title:"Why this is different from a platform implementation",copy:"Averin does not begin by assuming the retailer needs another application or that its current planning platform is wrong. The diagnostic works across Blue Yonder, o9, ERP, Excel or internal tools and focuses on decision evidence.",items:["Vendor-independent assessment","No new application deployment for V1","Existing-tool recommendations explicitly evaluated","Planner overrides treated as valuable decision evidence","Actual execution captured separately","AI recommended only where it solves a demonstrated decision problem"]},
      {title:"What happens after the diagnostic",copy:"Only if the analysis proves enough value should automation become a technology project.",items:["Improve existing rules or configuration","Implement better exception prioritization","Add recommendations inside an already approved BI or data environment","Integrate improvements into Blue Yonder, o9 or another existing planning workflow","Introduce AI explanation / triage with governance","Move toward assisted or controlled automation only when evidence supports it"]}
    ],
    cta:"Want an independent view of one replenishment decision?"
  },
  services: {
    eyebrow:"SERVICES", title:"Focused retail planning advisory—led by replenishment decision diagnostics.", description:"Averin's primary offer is the Inventory Replenishment Decision Diagnostic. Broader advisory is available when findings expand into assortment planning, merchandise financial planning, allocation, data management or AI.",
    sections:[
      {title:"Inventory Replenishment Decision Diagnostic",copy:"Assess one recurring replenishment decision using the retailer's existing data, current-tool recommendations, planner overrides and execution history—without deploying a new application.",items:["Decision mapping","Exception analysis","Current-tool recommendation comparison","Planner override analysis","Decision workbook","Historical / policy assessment","AI and automation roadmap"]},
      {title:"Assortment Planning Advisory",copy:"Improve pre-season and in-season assortment decisions with clearer planning logic, localization, clustering and planner workflows.",items:["Assortment architecture","Breadth and depth","Localization and clustering","Size profiling","In-season assortment decisions","Process and workflow design"]},
      {title:"Merchandise Financial Planning Advisory",copy:"Strengthen financial planning logic, measures and decision processes from strategic targets through OTB and scenario management.",items:["Sales, margin and markdown planning","Inventory, receipts and OTB","AUR, AUC and unit economics","Measure dependencies","What holds and what flexes","Scenario and reconciliation logic"]},
      {title:"Data Management & AI Advisory",copy:"Create the data foundation required for reliable planning and apply AI where it can materially improve decisions across assortment, MFP, allocation and replenishment.",items:["Planning data models","Hierarchies, attributes and measures","Data quality and reconciliation","Integration requirements","AI use-case prioritization","Decision intelligence and adoption roadmap"]}
    ]
  },
  capabilities:{eyebrow:"CAPABILITIES",title:"Four areas of specialized retail planning expertise.",description:"Averin is deliberately focused on the planning decisions, data and technology that matter most across assortment planning, merchandise financial planning, allocation and replenishment.",sections:[
    {title:"Assortment Planning",copy:"Pre-season and in-season assortment planning designed around the decisions merchants and planners actually make.",items:["Assortment architecture","Option counts and breadth/depth","Store and channel clustering","Localization","Price architecture","Size profiling and buy quantities","Sell-through and rate of sale","In-season assortment actions"]},
    {title:"Merchandise Financial Planning",copy:"Financial planning logic and process design across sales, margin, inventory and receipts.",items:["Sales, units, AUR and AUC","Margin, markdown and COGS","Inventory, receipts and OTB","Turns, GMROI and scenarios","Top-down and bottom-up reconciliation","Measure dependencies","Hold/flex behavior"]},
    {title:"Allocation & Replenishment",copy:"Inventory positioning and replenishment decisions from initial allocation through ongoing store and channel execution.",items:["Initial allocation","Store eligibility","Presentation minimums","Size curves and packs","Inventory position","Target inventory","Replenishment logic","Current-tool recommendation review","Planner overrides","Prioritization, exceptions and execution"]},
    {title:"Data Management & AI Advisory",copy:"Planning data architecture and practical AI advisory designed specifically around assortment, MFP, allocation and replenishment.",items:["Planning hierarchies and attributes","Measure definitions and governance","Data quality and reconciliation","Planning integrations","AI readiness","Decision intelligence","Human approval and control design","Outcome-learning roadmap"]}
  ]},
  "technology-advisory":{eyebrow:"PLANNING TECHNOLOGY ADVISORY",title:"Select planning technology with confidence.",description:"Averin provides vendor-neutral software-selection support for assortment planning, merchandise financial planning, allocation and replenishment, with data and AI requirements evaluated as part of the solution.",sections:[
    {title:"Compare planning decisions—not feature lists.",copy:"We define common business scenarios so platforms are evaluated against the same assortment, MFP, allocation and replenishment decisions, data needs, workflows and business outcomes."},
    {title:"Selection Method",items:["Current-state assessment","Capability requirements","Functional requirements","Data and integration requirements","AI and decision-intelligence requirements","Vendor longlist and shortlist","RFI / RFP","Scripted demonstrations","Scoring and TCO","Architecture assessment","Recommendation and roadmap"]},
    {title:"Vendor-neutral by design",copy:"The objective is fit—not a predetermined vendor. Evaluations consider planning capability, data fit, user experience, implementation risk, TCO and long-term operating needs."}
  ],cta:"Planning a software evaluation?"},
  "ai-retail-planning":{eyebrow:"DATA MANAGEMENT & AI ADVISORY",title:"Build trusted planning data first. Apply AI where it improves decisions.",description:"Averin helps retailers strengthen the data foundations behind assortment planning, MFP, allocation and replenishment, then apply AI around explicit planning decisions rather than generic analysis.",sections:[
    {title:"Decision-First AI",copy:"Start with a recurring planning decision, the current system recommendation, planner judgment and outcome evidence before deciding whether AI should observe, prioritize, recommend or act.",items:["Decision mapping","Current-tool recommendation capture","Planner override capture","Exception taxonomy","Recommendation boundaries","Outcome measurement"]},
    {title:"Planning Data Foundation",copy:"Define the hierarchies, attributes, measures, grain and governance required for reliable planning decisions.",items:["Product and location hierarchies","Planning measures","Attribute strategy","Calendar and time grain","Data ownership","Quality and reconciliation rules"]},
    {title:"AI Decision Intelligence",copy:"Move beyond dashboards toward systems that prioritize exceptions, explain recommendations, remember decision context and improve over time.",items:["Exception prioritization","Override-pattern analysis","Decision-memory design","Scenario intelligence","Explainable recommendations","Recommendation vs outcome learning"]},
    {title:"AI Governance & Adoption",copy:"Define where AI should observe, recommend or act, with explicit controls around consequential planning decisions.",items:["Human approval boundaries","Confidence thresholds","Audit trails","Outcome measurement","Planner feedback loops","Responsible automation"]}
  ]},
  "health-check":{eyebrow:"RETAIL PLANNING HEALTH CHECK™",title:"Find out where planning is getting stuck—and what to improve next.",description:"A focused independent diagnostic across assortment planning, MFP, allocation and replenishment, together with the data and AI capabilities supporting those processes.",sections:[
    {title:"What We Assess",items:["Assortment planning process and decisions","Merchandise financial planning measures and dependencies","Allocation and replenishment logic","Planning data, hierarchies and KPIs","Technology and integration","AI readiness and decision intelligence"]},
    {title:"Maturity Model",items:["Level 1 — Reactive: manual and spreadsheet-heavy","Level 2 — Standardized: defined processes and measures","Level 3 — Integrated: connected planning processes and shared data","Level 4 — Predictive: stronger analytics, optimization and exception management","Level 5 — Adaptive: AI-assisted, evidence-driven planning decisions"]},
    {title:"Typical Deliverables",items:["Executive summary and maturity score","Capability heatmap across the four focus areas","Top process and decision gaps","Data, measure and hierarchy observations","Technology and integration observations","AI opportunities and readiness constraints","Quick wins and prioritized roadmap"]}
  ],cta:"Start with an independent planning diagnostic."},
  about:{eyebrow:"ABOUT AVERIN",title:"Practitioner-led retail planning advisory with a deliberate focus.",description:"Averin's primary market offer is the Inventory Replenishment Decision Diagnostic, backed by deep experience across assortment planning, merchandise financial planning, allocation and replenishment, planning data and AI.",sections:[
    {title:"Built around the decisions planners actually make.",copy:"Our approach combines retail-planning expertise, solution architecture, data discipline and modern AI methods. The objective is practical: improve real planning decisions rather than add another layer of generic analytics."},
    {title:"Independent",copy:"Averin can evaluate replenishment decisions across existing planning platforms and manual workflows without being tied to a software vendor's implementation approach."},
    {title:"Evidence-led",copy:"Current-tool recommendations, planner overrides, actual execution and later outcomes are treated as separate evidence rather than assuming one source is always correct."},
    {title:"Modern",copy:"Traditional retail-planning discipline combined with data management, decision intelligence, optimization and AI."},
    {title:"Our Principles",items:["Design the decision before the workflow","Evaluate the current system before adding another one","Treat planner overrides as evidence, not noise","Back-test before scaling automation","Use AI where judgment can be augmented responsibly"]}
  ]},
  insights:{eyebrow:"AVERIN INSIGHTS",title:"Practical thinking for retail planning leaders.",description:"Perspectives focused on replenishment decision intelligence, assortment planning, merchandise financial planning, allocation, planning data and AI.",sections:[
    {title:"What Planner Overrides Can Tell You About Replenishment",copy:"Why repeated overrides can reveal policy, data, configuration and exception-management gaps—and become useful future decision evidence."},
    {title:"From Replenishment Report to Exception Decision System",copy:"Why the next step in retail planning is not another dashboard, but a prioritized decision workflow built around action."},
    {title:"When Should Retailers Allocate Versus Replenish Inventory?",copy:"Understanding the different decisions, constraints and planning logic behind allocation and replenishment."},
    {title:"Why Merchandise Financial Planning Transformations Fail",copy:"Common failure modes across measures, dependencies, planning levels, operating model and implementation design."},
    {title:"Why Planning Data Design Matters Before AI",copy:"AI recommendations are only as reliable as the hierarchies, measures, dependencies, policies and data quality underneath them."},
    {title:"What an Adaptive Planning Agent Should Actually Learn",copy:"Why decision history, planner overrides and outcome learning can be more valuable than another conversational planning assistant."}
  ]},
  contact:{eyebrow:"CONTACT",title:"Start with one replenishment decision.",description:"If your team uses an existing tool plus planner judgment to decide what to replenish, hold, transfer or investigate, Averin can independently assess that decision using an agreed data extract—without requiring a new production application.",sections:[
    {title:"Inventory Replenishment Decision Diagnostic",items:["Focused decision scope","No new application deployment required for V1","Works with practical Excel, CSV, POS or planning exports","Current-tool recommendation analysis","Planner override and execution analysis","Priority exception workbook","Historical / policy assessment where data permits","AI and automation roadmap"]},
    {title:"Other reasons to reach out",items:["Your assortment planning process needs redesign","Your MFP measures, dependencies or OTB logic need improvement","Your allocation or replenishment process needs redesign","Your planning data is difficult to reconcile or govern","You are selecting a planning platform","You are defining practical AI use cases around planning decisions"]}
  ]}
};

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=pages[slug];return p?{title:p.title,description:p.description}:{} }
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}))}

export default async function DynamicPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params; const p=pages[slug]; if(!p) notFound();
  const email=process.env.NEXT_PUBLIC_CONTACT_EMAIL||"info@averinconsulting.com";
  const isDiagnostic=slug==="inventory-replenishment-sprint";
  return <><PageHero eyebrow={p.eyebrow} title={p.title} description={p.description}>{(slug==="health-check"||isDiagnostic)&&<div className="hero-actions">{isDiagnostic?<><Link className="button button-gold" href="/contact">Discuss a Diagnostic</Link><Link className="button button-outline-light" href="/contact">Share Your Decision Challenge</Link></>:<Link className="button" href="/contact">Request a Planning Health Check</Link>}</div>}</PageHero>
    <section className="section"><div className="container card-grid two">{p.sections.map((s,i)=><article className="card" key={s.title}><span className="card-number">{String(i+1).padStart(2,"0")}</span><h3>{s.title}</h3>{s.copy&&<p>{s.copy}</p>}{s.items&&<ul>{s.items.map(x=><li key={x}>{x}</li>)}</ul>}{slug==="insights"&&<span className="text-link">Article coming soon →</span>}</article>)}</div></section>
    {slug==="contact"?<section className="section section-soft"><div className="container"><div className="contact-box"><p className="eyebrow light">CONTACT AVERIN</p><h2>Discuss your replenishment decision.</h2><p>Email Averin with a short description of the replenishment decision, the current system or report used today, the planner role involved and the outcome you want to improve.</p><div className="contact-details"><a href={`mailto:${email}?subject=Inventory%20Replenishment%20Decision%20Diagnostic`}>{email}</a></div></div></div></section>:<CTA title={p.cta}/>}</>;
}
