import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { CTA, PageHero } from "@/components/SiteShell";

type PageData = { eyebrow:string; title:string; description:string; sections:{title:string; copy?:string; items?:string[]}[]; cta?:string };

const pages: Record<string, PageData> = {
  "inventory-replenishment-sprint": {
    eyebrow:"PRIMARY OFFERING", title:"Inventory Replenishment & Exception Decision Sprint", description:"A focused two-week engagement that turns one recurring replenishment decision into a working AI-assisted decision prototype using your own sales and inventory data.",
    sections:[
      {title:"The decision we improve",copy:"Most retailers already have reports. The harder problem is deciding what actually needs attention and what action to take. The sprint focuses on the recurring weekly decision: replenish, hold, transfer or investigate.",items:["Which SKU-location combinations are at genuine stockout risk?","Where is inventory building faster than demand?","What should be replenished now versus monitored?","Which exceptions deserve planner attention?","What decision rules are planners already using implicitly?"]},
      {title:"What data we use",copy:"The sprint is designed to start with practical data already available to the retailer rather than waiting for a large data transformation.",items:["SKU / product identifier","Store, channel or location","Sales history","Current on-hand inventory","Incoming / open inventory where available","Price and cost where useful","Lead time or replenishment cadence","Existing target-stock, WOS or business-rule fields where available"]},
      {title:"What Averin builds",copy:"The output is a decision prototype, not a generic dashboard or chatbot.",items:["Replenishment Decision Map","Explicit thresholds, constraints and exception logic","Prioritized exception list","Explainable recommended actions","Historical back-test on prior periods","90-day AI adoption and operating-model plan"]},
      {title:"How the two weeks work",items:["Days 1–2 — observe the current planner / buyer workflow and select one decision","Days 3–5 — map the decision logic, data and exceptions","Days 6–8 — build the working decision prototype on retailer data","Days 9–10 — back-test, review with the planner and refine recommendations","Final readout — findings, prototype, adoption path and next-step recommendation"]},
      {title:"Why this is not replaceable by a generic AI prompt",copy:"A prompt can explain replenishment principles. It cannot know how your team actually decides, which data is trusted, what constraints apply, what exceptions matter or whether the resulting recommendations would have worked on your historical data.",items:["Retailer-specific decision logic","Retailer-specific data context","Planner workflow and judgment","Explicit constraints and controls","Historical evidence through back-testing","Reusable decision IP rather than one-time analysis"]},
      {title:"Commercial model",copy:"The standard sprint is deliberately small enough to approve and execute without a large transformation program.",items:["CAD $5,000 fixed professional fee","Approximately two weeks","One replenishment / exception decision","One working prototype","One historical back-test","One 90-day adoption plan","Limited design-partner pilot may be available for a selected retailer in exchange for feedback and permission to use anonymized learnings"]}
    ],
    cta:"Want to test one replenishment decision on your own data?"
  },
  services: {
    eyebrow:"SERVICES", title:"Focused retail planning advisory—led by replenishment decision intelligence.", description:"Averin&apos;s primary offer is the Inventory Replenishment & Exception Decision Sprint. Broader advisory is available when the work expands into assortment planning, merchandise financial planning, allocation, data or AI.",
    sections:[
      {title:"Inventory Replenishment & Exception Decision Sprint",copy:"Turn one recurring replenishment decision into a working AI-assisted decision prototype using your own data.",items:["Decision mapping","Exception logic","Prioritized recommendations","Historical back-test","90-day AI adoption plan","CAD $5,000 fixed-fee standard sprint"]},
      {title:"Assortment Planning Advisory",copy:"Improve pre-season and in-season assortment decisions with clearer planning logic, localization, clustering and planner workflows.",items:["Assortment architecture","Breadth and depth","Localization and clustering","Size profiling","In-season assortment decisions","Process and workflow design"]},
      {title:"Merchandise Financial Planning Advisory",copy:"Strengthen financial planning logic, measures and decision processes from strategic targets through OTB and scenario management.",items:["Sales, margin and markdown planning","Inventory, receipts and OTB","AUR, AUC and unit economics","Measure dependencies","What holds and what flexes","Scenario and reconciliation logic"]},
      {title:"Data Management & AI Advisory",copy:"Create the data foundation required for reliable planning and apply AI where it can materially improve decisions across assortment, MFP, allocation and replenishment.",items:["Planning data models","Hierarchies, attributes and measures","Data quality and reconciliation","Integration requirements","AI use-case prioritization","Adaptive planning and decision intelligence"]}
    ]
  },
  capabilities:{eyebrow:"CAPABILITIES",title:"Four areas of specialized retail planning expertise.",description:"Averin is deliberately focused on the planning decisions, data and technology that matter most across assortment planning, merchandise financial planning, allocation and replenishment.",sections:[
    {title:"Assortment Planning",copy:"Pre-season and in-season assortment planning designed around the decisions merchants and planners actually make.",items:["Assortment architecture","Option counts and breadth/depth","Store and channel clustering","Localization","Price architecture","Size profiling and buy quantities","Sell-through and rate of sale","In-season assortment actions"]},
    {title:"Merchandise Financial Planning",copy:"Financial planning logic and process design across sales, margin, inventory and receipts.",items:["Sales, units, AUR and AUC","Margin, markdown and COGS","Inventory, receipts and OTB","Turns, GMROI and scenarios","Top-down and bottom-up reconciliation","Measure dependencies","Hold/flex behavior"]},
    {title:"Allocation & Replenishment",copy:"Inventory positioning and replenishment decisions from initial allocation through ongoing store and channel execution.",items:["Initial allocation","Store eligibility","Presentation minimums","Size curves and packs","Inventory position","Target inventory","Replenishment logic","Prioritization, exceptions and overrides"]},
    {title:"Data Management & AI Advisory",copy:"Planning data architecture and practical AI advisory designed specifically around assortment, MFP, allocation and replenishment.",items:["Planning hierarchies and attributes","Measure definitions and governance","Data quality and reconciliation","Planning integrations","AI readiness","Decision intelligence","Adaptive planning agents","Human approval and control design"]}
  ]},
  "technology-advisory":{eyebrow:"PLANNING TECHNOLOGY ADVISORY",title:"Select planning technology with confidence.",description:"Averin provides vendor-neutral software-selection support for assortment planning, merchandise financial planning, allocation and replenishment, with data and AI requirements evaluated as part of the solution.",sections:[
    {title:"Compare planning decisions—not feature lists.",copy:"We define common business scenarios so platforms are evaluated against the same assortment, MFP, allocation and replenishment decisions, data needs, workflows and business outcomes."},
    {title:"Selection Method",items:["Current-state assessment","Capability requirements","Functional requirements","Data and integration requirements","AI and decision-intelligence requirements","Vendor longlist and shortlist","RFI / RFP","Scripted demonstrations","Scoring and TCO","Architecture assessment","Recommendation and roadmap"]},
    {title:"Vendor-neutral by design",copy:"The objective is fit—not a predetermined vendor. Evaluations consider planning capability, data fit, user experience, implementation risk, TCO and long-term operating needs."}
  ],cta:"Planning a software evaluation?"},
  "ai-retail-planning":{eyebrow:"DATA MANAGEMENT & AI ADVISORY",title:"Build trusted planning data first. Apply AI where it improves decisions.",description:"Averin helps retailers strengthen the data foundations behind assortment planning, MFP, allocation and replenishment, then apply AI around explicit planning decisions rather than generic analysis.",sections:[
    {title:"Decision-First AI",copy:"Start with a recurring planning decision, make the inputs, constraints and desired action explicit, and only then determine where AI should observe, prioritize, recommend or act.",items:["Decision mapping","Planner workflow observation","Exception taxonomy","Recommendation boundaries","Human approval design","Outcome measurement"]},
    {title:"Planning Data Foundation",copy:"Define the hierarchies, attributes, measures, grain and governance required for reliable planning decisions.",items:["Product and location hierarchies","Planning measures","Attribute strategy","Calendar and time grain","Data ownership","Quality and reconciliation rules"]},
    {title:"AI Decision Intelligence",copy:"Move beyond dashboards toward systems that prioritize exceptions, explain recommendations, remember decision context and improve over time.",items:["Exception prioritization","Intent inference","Decision-memory design","Adaptive planning agents","Scenario intelligence","Explainable recommendations"]},
    {title:"AI Governance & Adoption",copy:"Define where AI should observe, recommend or act, with explicit controls around consequential planning decisions.",items:["Human approval boundaries","Confidence thresholds","Audit trails","Outcome measurement","Planner feedback loops","Responsible automation"]}
  ]},
  "health-check":{eyebrow:"RETAIL PLANNING HEALTH CHECK™",title:"Find out where planning is getting stuck—and what to improve next.",description:"A focused independent diagnostic across assortment planning, MFP, allocation and replenishment, together with the data and AI capabilities supporting those processes.",sections:[
    {title:"What We Assess",items:["Assortment planning process and decisions","Merchandise financial planning measures and dependencies","Allocation and replenishment logic","Planning data, hierarchies and KPIs","Technology and integration","AI readiness and decision intelligence"]},
    {title:"Maturity Model",items:["Level 1 — Reactive: manual and spreadsheet-heavy","Level 2 — Standardized: defined processes and measures","Level 3 — Integrated: connected planning processes and shared data","Level 4 — Predictive: stronger analytics, optimization and exception management","Level 5 — Adaptive: AI-assisted, evidence-driven planning decisions"]},
    {title:"Typical Deliverables",items:["Executive summary and maturity score","Capability heatmap across the four focus areas","Top process and decision gaps","Data, measure and hierarchy observations","Technology and integration observations","AI opportunities and readiness constraints","Quick wins and prioritized roadmap"]}
  ],cta:"Start with an independent planning diagnostic."},
  about:{eyebrow:"ABOUT AVERIN",title:"Practitioner-led retail planning advisory with a deliberate focus.",description:"Averin&apos;s primary market offer is the Inventory Replenishment & Exception Decision Sprint, backed by deep experience across assortment planning, merchandise financial planning, allocation and replenishment, planning data and AI.",sections:[
    {title:"Built around the decisions planners actually make.",copy:"Our approach combines retail-planning expertise, solution architecture, data discipline and modern AI methods. The objective is practical: improve real planning decisions rather than add another layer of generic analytics."},
    {title:"Decision-first",copy:"We start with the business decision, the planner workflow and the data required to make that decision well."},
    {title:"Independent",copy:"Vendor-neutral advice based on client requirements, fit and measurable outcomes."},
    {title:"Modern",copy:"Traditional retail-planning discipline combined with data management, decision intelligence, optimization and AI."},
    {title:"Our Principles",items:["Design the decision before the workflow","Make planning measures and dependencies explicit","Treat trusted data as a prerequisite for AI","Back-test recommendations before scaling automation","Keep consequential decisions human-controlled until evidence supports greater autonomy"]}
  ]},
  insights:{eyebrow:"AVERIN INSIGHTS",title:"Practical thinking for retail planning leaders.",description:"Perspectives focused on replenishment decision intelligence, assortment planning, merchandise financial planning, allocation, planning data and AI.",sections:[
    {title:"From Replenishment Report to Exception Decision System",copy:"Why the next step in retail planning is not another dashboard, but a prioritized decision workflow built around action."},
    {title:"When Should Retailers Allocate Versus Replenish Inventory?",copy:"Understanding the different decisions, constraints and planning logic behind allocation and replenishment."},
    {title:"Why Merchandise Financial Planning Transformations Fail",copy:"Common failure modes across measures, dependencies, planning levels, operating model and implementation design."},
    {title:"Pre-Season vs In-Season Assortment Planning",copy:"How decision cadence, signals and actions should evolve once the season is underway."},
    {title:"Why Planning Data Design Matters Before AI",copy:"AI recommendations are only as reliable as the hierarchies, measures, dependencies, policies and data quality underneath them."},
    {title:"What an Adaptive Planning Agent Should Actually Learn",copy:"Why planner edit sequences, decision memory and outcome learning can be more valuable than another conversational planning assistant."}
  ]},
  contact:{eyebrow:"CONTACT",title:"Start with one replenishment decision.",description:"If your team spends time reviewing sales and inventory to decide what to replenish, hold, transfer or investigate, Averin can start with that one recurring decision and test it on your existing data.",sections:[
    {title:"Inventory Replenishment & Exception Decision Sprint",items:["Two-week focused engagement","CAD $5,000 fixed-fee standard offer","Works with practical Excel, CSV, POS or planning exports","Decision map + exception prototype","Historical back-test","90-day AI adoption plan","Limited design-partner pilot may be available"]},
    {title:"Other reasons to reach out",items:["Your assortment planning process needs redesign","Your MFP measures, dependencies or OTB logic need improvement","Your allocation or replenishment process needs redesign","Your planning data is difficult to reconcile or govern","You are selecting a planning platform","You are defining practical AI or adaptive-agent use cases"]}
  ]}
};

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=pages[slug];return p?{title:p.title,description:p.description}:{} }
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}))}

export default async function DynamicPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params; const p=pages[slug]; if(!p) notFound();
  const email=process.env.NEXT_PUBLIC_CONTACT_EMAIL||"info@averinconsulting.com";
  const isSprint=slug==="inventory-replenishment-sprint";
  return <><PageHero eyebrow={p.eyebrow} title={p.title} description={p.description}>{(slug==="health-check"||isSprint)&&<div className="hero-actions">{isSprint?<><Link className="button button-gold" href="/contact">Apply for Design Partner Pilot</Link><Link className="button button-outline-light" href="/contact">Discuss the $5,000 Sprint</Link></>:<Link className="button" href="/contact">Request a Planning Health Check</Link>}</div>}</PageHero>
    <section className="section"><div className="container card-grid two">{p.sections.map((s,i)=><article className="card" key={s.title}><span className="card-number">{String(i+1).padStart(2,"0")}</span><h3>{s.title}</h3>{s.copy&&<p>{s.copy}</p>}{s.items&&<ul>{s.items.map(x=><li key={x}>{x}</li>)}</ul>}{slug==="insights"&&<span className="text-link">Article coming soon →</span>}</article>)}</div></section>
    {slug==="contact"?<section className="section section-soft"><div className="container"><div className="contact-box"><p className="eyebrow light">CONTACT AVERIN</p><h2>Discuss your replenishment decision.</h2><p>Email Averin with a short description of the inventory or replenishment decision your team makes today, the data you currently use and the outcome you want to improve.</p><div className="contact-details"><a href={`mailto:${email}?subject=Inventory%20Replenishment%20Decision%20Sprint`}>{email}</a></div></div></div></section>:<CTA title={p.cta}/>}</>;
}
